name: split-monorepo
on:
  release:
    types: [published]

jobs:
  split-hook-dd-trace:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone "$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE" && git checkout "$GITHUB_SHA"
      - name: push-hook-dd-trace
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          targetOrg: open-feature-php
          targetRepo: dd-trace-hook
          targetBranch: ${{ github.event.release.tag_name }}
          filterArguments: '--subdirectory-filter hooks/DDTrace/'

  split-hook-otel:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone "$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE" && git checkout "$GITHUB_SHA"
      - name: push-hook-otel
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          targetOrg: open-feature-php
          targetRepo: otel-hook
          targetBranch: ${{ github.event.release.tag_name }}
          filterArguments: '--subdirectory-filter hooks/OpenTelemetry/'

  split-hook-validator:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone "$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE" && git checkout "$GITHUB_SHA"
      - name: push-hook-validator
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          targetOrg: open-feature-php
          targetRepo: validators-hook
          targetBranch: ${{ github.event.release.tag_name }}
          filterArguments: '--subdirectory-filter hooks/Validators/'

  split-provider-cloudbees:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone "$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE" && git checkout "$GITHUB_SHA"
      - name: push-provider-cloudbees
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          targetOrg: open-feature-php
          targetRepo: cloudbees-provider
          targetBranch: ${{ github.event.release.tag_name }}
          filterArguments: '--subdirectory-filter providers/CloudBees/'

  split-provider-flagd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone "$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE" && git checkout "$GITHUB_SHA"
      - name: push-provider-flagd
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          targetOrg: open-feature-php
          targetRepo: flagd-provider
          targetBranch: ${{ github.event.release.tag_name }}
          filterArguments: '--subdirectory-filter providers/Flagd/'

  split-provider-split:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone "$GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE" && git checkout "$GITHUB_SHA"
      - name: push-provider-split
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          targetOrg: open-feature-php
          targetRepo: split-provider
          targetBranch: ${{ github.event.release.tag_name }}
          filterArguments: '--subdirectory-filter providers/Split/'
